export const en = {
  about: 'created to help teams and users effectively complete their tasks',
  team: 'Our team:',
  toMain: 'go to main page',
  signin: 'sign in',
  signup: 'sign up',
  names: ['Sergey', 'Ravganiyat', 'Elena'],
  jobs: ['Project build. CI/CD.', 'Authorization.', 'Welcome page'],
  gitHubLink: 'View Github',
  addBoard: 'Add new board',
  editUser: 'Edit User profile',
  signOut: 'Sign Out',
  boardList: "Board's list",
  addNewBoard: {
    addTitle: 'Add title for new board',
    title: 'title',
  },
  board: 'Board',
  errors: {
    titleLength: 'The title must be between 3 and 30 characters.',
    required: 'This field is required!',
    userNameLength: 'The username must be between 3 and 20 characters.',
    passwLength: 'The password must be between 6 and 10 characters.',
    wrongEmail: 'This is not a valid email.',
  },
  buttons: {
    cancel: 'cancel',
    add: '+ add',
    delete: 'delete',
    deleteUser: 'delete user',
    submit: 'submit',
    signOut: 'sign out',
    signIn: 'sign in',
    signUp: 'sign up',
    save: 'save changes',
    delAcc: 'delete account',
    redirect: 'go to',
    addTask: 'add task',
  },
  deletePopup: {
    title: 'Delete Confirmation',
    description: 'Are you sure to delete user?',
  },
  deleteColumn: {
    title: 'Delete Confirmation',
    description: 'Are you sure to delete column',
  },
  deleteTask: {
    title: 'Delete Confirmation',
    description: 'Are you sure to delete task',
  },
  redirectionPopup: {
    title: 'Redirect Confirmation',
    description: 'Do you want to go to the main page?',
  },
  editProfilePopup: {
    title: 'Edit Profile',
    description: 'To Edit Profile, please change content of all form fields.',
  },
  signOutPopup: {
    title: 'Sign Out',
    description: 'Are you sure you want to sign out?',
  },
  signInDialog: {
    title: 'Sign In',
    havntAcc: "Don't have an account? Sign Up",
  },
  formFieldsLabels: {
    email: 'Email',
    passw: 'Password',
    userName: 'Username',
  },
  signUpDialog: {
    title: 'Sign Up',
  },
  accSettings: {
    title: 'Account Settings',
    discription: 'To Edit Profile, please change content of all form fields.',
    succes: 'Success',
  },
  addNewTask: {
    header: 'Add new task',
    title: 'title',
    description: 'description',
    user: 'user',
  },
};
